export type IComponents =
  | "Button"
  | "CloseButton"
  | "Accordion"
  | "Divider"
  | "Alert"
  | "Spinner"
  | "Center"
  | "Flex"
  | "Dialog"
  | "LoadingOverlay"
  | "Modal"
  | "Tooltip"
  | "ClickAwayListener"
  | "ThemeProvider";
