import GET_BACKGROUND_ACCENT from "./GET_BACKGROUND_ACCENT";
import GET_BACKGROUND_HOVER from "./GET_BACKGROUND_HOVER";
import GET_BACKGROUND from "./GET_BACKGROUND";
import GET_BORDER from "./GET_BORDER";
import GET_COLOR_HOVER from "./GET_COLOR_HOVER";
import GET_COLOR from "./GET_COLOR";
import GET_CONTRAST_FONT from "./GET_CONTRAST_FONT";
import GET_FONT_DIMMED from "./GET_FONT_DIMMED";
import GET_FONT from "./GET_FONT";

export {
  GET_BACKGROUND_ACCENT,
  GET_BACKGROUND_HOVER,
  GET_BACKGROUND,
  GET_BORDER,
  GET_COLOR_HOVER,
  GET_COLOR,
  GET_CONTRAST_FONT,
  GET_FONT_DIMMED,
  GET_FONT,
};
